In [0]:
import torch

In [0]:
def activation(x):
  # sigmoid activation funcction
  return 1 / (1 + torch.exp(-x))

In [0]:
# generate a random seed so thigs are predictable
torch.manual_seed(7)
# feature are 5 random variables
features = torch.randn((1, 5))
# true weigths are our data, random normal variables again
weigths =  torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

In [0]:
# create logits
y = activation(torch.sum(features * weigths) + bias)
y = activation((features*weigths).sum() + bias)

In [0]:
y = activation(torch.mm(features, weigths.view(5, 1)) + bias)

In [0]:
# generate  some data
torch.manual_seed(7)
# features are 3 random normal variables
features = torch.randn((1, 3))
# definee the size of each layer in our network
n_input = features.shape[1]
n_hidden = 2
n_output = 1

# weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# weights for hidden layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and oputput layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [14]:
h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[0.3171]])


In [15]:
# numpy to torh and back
import numpy as np
a = np.random.rand(4, 3)
print(a)

[[0.53605519 0.10019823 0.1998179 ]
 [0.58622757 0.16528477 0.92292214]
 [0.93276869 0.06208106 0.28881502]
 [0.60985848 0.83741873 0.61330124]]


In [16]:
b = torch.from_numpy(a)
print(b)

tensor([[0.5361, 0.1002, 0.1998],
        [0.5862, 0.1653, 0.9229],
        [0.9328, 0.0621, 0.2888],
        [0.6099, 0.8374, 0.6133]], dtype=torch.float64)


In [17]:
type(b)

torch.Tensor

In [18]:
b.numpy()

array([[0.53605519, 0.10019823, 0.1998179 ],
       [0.58622757, 0.16528477, 0.92292214],
       [0.93276869, 0.06208106, 0.28881502],
       [0.60985848, 0.83741873, 0.61330124]])

In [19]:
type(b.numpy())

numpy.ndarray

In [21]:
b.mul_(2)

tensor([[1.0721, 0.2004, 0.3996],
        [1.1725, 0.3306, 1.8458],
        [1.8655, 0.1242, 0.5776],
        [1.2197, 1.6748, 1.2266]], dtype=torch.float64)

In [22]:
a

array([[1.07211038, 0.20039647, 0.39963579],
       [1.17245514, 0.33056953, 1.84584428],
       [1.86553738, 0.12416212, 0.57763003],
       [1.21971695, 1.67483747, 1.22660247]])